var annotated_dup =
[
    [ "docstring", "namespacedocstring.html", [
      [ "PyClass", "classdocstring_1_1PyClass.html", "classdocstring_1_1PyClass" ]
    ] ],
    [ "LE", null, [
      [ "GUI", null, [
        [ "Component", "classLE_1_1GUI_1_1Component.html", "classLE_1_1GUI_1_1Component" ],
        [ "Container", "classLE_1_1GUI_1_1Container.html", "classLE_1_1GUI_1_1Container" ],
        [ "Font", "classLE_1_1GUI_1_1Font.html", "classLE_1_1GUI_1_1Font" ],
        [ "Manager", "classLE_1_1GUI_1_1Manager.html", "classLE_1_1GUI_1_1Manager" ],
        [ "Text", "classLE_1_1GUI_1_1Text.html", "classLE_1_1GUI_1_1Text" ]
      ] ],
      [ "Shapes", null, [
        [ "Rectangle", "classLE_1_1Shapes_1_1Rectangle.html", "classLE_1_1Shapes_1_1Rectangle" ],
        [ "Shape", "classLE_1_1Shapes_1_1Shape.html", "classLE_1_1Shapes_1_1Shape" ],
        [ "Triangle", "classLE_1_1Shapes_1_1Triangle.html", "classLE_1_1Shapes_1_1Triangle" ]
      ] ],
      [ "Clock", "classLE_1_1Clock.html", "classLE_1_1Clock" ],
      [ "Color", "classLE_1_1Color.html", "classLE_1_1Color" ],
      [ "Engine", "classLE_1_1Engine.html", "classLE_1_1Engine" ],
      [ "Error", "classLE_1_1Error.html", "classLE_1_1Error" ],
      [ "EventManager", "classLE_1_1EventManager.html", "classLE_1_1EventManager" ],
      [ "Key", "structLE_1_1Key.html", null ],
      [ "Matrix", "classLE_1_1Matrix.html", "classLE_1_1Matrix" ],
      [ "Scene", "classLE_1_1Scene.html", "classLE_1_1Scene" ],
      [ "SceneManager", "classLE_1_1SceneManager.html", "classLE_1_1SceneManager" ],
      [ "Shader", "classLE_1_1Shader.html", "classLE_1_1Shader" ],
      [ "Status", "structLE_1_1Status.html", null ],
      [ "Vector2", "classLE_1_1Vector2.html", "classLE_1_1Vector2" ],
      [ "Vector3", "classLE_1_1Vector3.html", "classLE_1_1Vector3" ],
      [ "Vector4", "classLE_1_1Vector4.html", "classLE_1_1Vector4" ],
      [ "Window", "classLE_1_1Window.html", "classLE_1_1Window" ]
    ] ],
    [ "pyexample", "namespacepyexample.html", [
      [ "PyClass", "classpyexample_1_1PyClass.html", "classpyexample_1_1PyClass" ]
    ] ],
    [ "_Entity", "struct__Entity.html", null ],
    [ "A", "classA.html", null ],
    [ "Afterdoc_Test", "classAfterdoc__Test.html", "classAfterdoc__Test" ],
    [ "AsioNetworkModule", "classAsioNetworkModule.html", "classAsioNetworkModule" ],
    [ "Autolink_Test", "classAutolink__Test.html", "classAutolink__Test" ],
    [ "B", "classB.html", null ],
    [ "Body", "structBody.html", null ],
    [ "Box", "structBox.html", "structBox" ],
    [ "Broker", "classBroker.html", "classBroker" ],
    [ "C", "classC.html", null ],
    [ "C1", "classC1.html", null ],
    [ "C2", "classC2.html", null ],
    [ "C3", "classC3.html", null ],
    [ "C4", "classC4.html", null ],
    [ "C5", "classC5.html", null ],
    [ "Car", "structCar.html", "structCar" ],
    [ "Client", "classClient.html", null ],
    [ "ClientBroker", "classClientBroker.html", "classClientBroker" ],
    [ "ComponentArray", "classComponentArray.html", "classComponentArray" ],
    [ "ComponentManager", "classComponentManager.html", "classComponentManager" ],
    [ "ComponentManagerError", "classComponentManagerError.html", "classComponentManagerError" ],
    [ "CoordStruct", "structCoordStruct.html", "structCoordStruct" ],
    [ "D", "classD.html", null ],
    [ "E", "classE.html", null ],
    [ "Ecs", "classEcs.html", "classEcs" ],
    [ "EntityManager", "classEntityManager.html", "classEntityManager" ],
    [ "EntityManagerError", "classEntityManagerError.html", "classEntityManagerError" ],
    [ "Enum_Test", "classEnum__Test.html", "classEnum__Test" ],
    [ "Example_Test", "classExample__Test.html", "classExample__Test" ],
    [ "Fn_Test", "classFn__Test.html", "classFn__Test" ],
    [ "GameClock", "classGameClock.html", null ],
    [ "GameScene", "classGameScene.html", "classGameScene" ],
    [ "Header", "structHeader.html", null ],
    [ "Health", "structHealth.html", null ],
    [ "HitBox", "structHitBox.html", null ],
    [ "HurtBox", "structHurtBox.html", null ],
    [ "IClient", "classIClient.html", null ],
    [ "IComponentArray", "classIComponentArray.html", "classIComponentArray" ],
    [ "IListenerTCP", "classIListenerTCP.html", null ],
    [ "IListenerUDP", "classIListenerUDP.html", null ],
    [ "Include_Test", "classInclude__Test.html", "classInclude__Test" ],
    [ "INetworkModule", "classINetworkModule.html", "classINetworkModule" ],
    [ "IServer", "classIServer.html", null ],
    [ "ISession", "classISession.html", null ],
    [ "Javadoc_Test", "classJavadoc__Test.html", "classJavadoc__Test" ],
    [ "ListenerTCP", "classListenerTCP.html", "classListenerTCP" ],
    [ "ListenerUDP", "classListenerUDP.html", "classListenerUDP" ],
    [ "LoaderLib", "classLoaderLib.html", "classLoaderLib" ],
    [ "LoaderLibError", "classLoaderLibError.html", null ],
    [ "Memgrp_Test", "classMemgrp__Test.html", "classMemgrp__Test" ],
    [ "Message", "classMessage.html", "classMessage" ],
    [ "Motion", "structMotion.html", "structMotion" ],
    [ "mux_using_with", "classmux__using__with.html", "classmux__using__with" ],
    [ "MyContainer", "classMyContainer.html", null ],
    [ "MyParentContainer", "classMyParentContainer.html", null ],
    [ "MyScene", "classMyScene.html", "classMyScene" ],
    [ "Object", "structObject.html", null ],
    [ "Overload_Test", "classOverload__Test.html", "classOverload__Test" ],
    [ "PackUnpack", "classPackUnpack.html", null ],
    [ "Par_Test", "classPar__Test.html", null ],
    [ "Position", "structPosition.html", null ],
    [ "QTstyle_Test", "classQTstyle__Test.html", "classQTstyle__Test" ],
    [ "Render2DSystem", "classRender2DSystem.html", "classRender2DSystem" ],
    [ "Request", "structRequest.html", null ],
    [ "ResponsibilityChain", "classResponsibilityChain.html", null ],
    [ "Server", "classServer.html", null ],
    [ "ServerBroker", "classServerBroker.html", "classServerBroker" ],
    [ "Session", "classSession.html", "classSession" ],
    [ "SessionManager", "classSessionManager.html", null ],
    [ "SomeNiceClass", "classSomeNiceClass.html", null ],
    [ "SpriteComponent", "structSpriteComponent.html", "structSpriteComponent" ],
    [ "String", "classString.html", "classString" ],
    [ "System", "classSystem.html", "classSystem" ],
    [ "SystemManager", "classSystemManager.html", "classSystemManager" ],
    [ "SystemManagerError", "classSystemManagerError.html", "classSystemManagerError" ],
    [ "Tag", "classTag.html", "classTag" ],
    [ "Test", "classTest.html", "classTest" ],
    [ "Test< T * >", "classTest_3_01T_01_5_01_4.html", "classTest_3_01T_01_5_01_4" ],
    [ "Test< void *, 200 >", "classTest_3_01void_01_5_00_01200_01_4.html", "classTest_3_01void_01_5_00_01200_01_4" ],
    [ "Topic", "classTopic.html", "classTopic" ],
    [ "TransformComponent", "structTransformComponent.html", null ],
    [ "Truck", "structTruck.html", "structTruck" ],
    [ "UpdateEcs", "structUpdateEcs.html", null ],
    [ "Vehicle", "structVehicle.html", "structVehicle" ]
];